version: '3.4'

services:
  ollama:
    image: ollama/ollama
    environment:
      OLLAMA_ORIGINS: '*' 
    ports:
      - 11434:11434
    volumes:
      - ollama:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: always


volumes:
  ollama:
