version: '3.9'

services:
  ollama:
    image: ollama/ollama:latest
    pull_policy: always
    environment:
      OLLAMA_ORIGINS: '*' 
    ports:
      - 11434:11434
    volumes:
      - ollama:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped
  ollama-webui:
    image: ghcr.io/open-webui/open-webui:main
    volumes:
      - open-webui:/app/backend/data
    depends_on:
      - ollama
    ports:
      - 8080:8080
    environment:
      OLLAMA_BASE_URL: http://ollama:11434
    restart: unless-stopped


volumes:
  ollama:
  open-webui:

